footprint: [[-0.4, -0.30], [-0.4, 0.30], [0.4, 0.30], [0.4, -0.30]]
footprint_padding: 0.01

robot_base_frame: base_link
update_frequency: 4.0
publish_frequency: 0.5
transform_tolerance: 0.5

resolution: 0.05

obstacle_range: 28.0
raytrace_range: 28.0

#layer definitions
static:
    map_topic: /map
    subscribe_to_updates: true

obstacles_laser:
    observation_sources: laser
    laser: {data_type: LaserScan, clearing: true, marking: true, topic: scan, inf_is_valid: true}

inflation:
    inflation_radius: 1.0
    # increasing the factor will decrease the resulting cost values
    # exponential rate at which the obstacle cost drops off (default: 10)
    cost_scaling_factor: 5.0  
